import random
proceed = [
    'i like apples so much',
    'this is so good!',
    'this is the best day of my life',
    'just got home!',
    'why did you do this',
    'what is the time today',
    'is the clock dying?',
    'the weather is beautiful today',
    'i need a cup of coffee',
    'let’s go for a walk in the park',
    'how was your weekend?',
    'i finished reading that book',
    'do you want to watch a movie',
    'have you seen the latest news',
    'the kids are playing outside',
    'i’m looking forward to the weekend',
    'can you help me with this',
    'what’s your favorite recipe',
    'i just bought a new gadget',
    'do you prefer tea or coffee',
    'the concert was amazing last night',
    'i’m planning a trip to Europe',
    'the garden needs some watering',
    'did you enjoy your meal',
    'it’s a great day for a hike',
    'i’m excited for the upcoming game',
    'the book was a real page-turner',
    'let’s meet up for lunch tomorrow',
    'i found a new hobby recently',
    'the view from the mountain was stunning',
    'i need to finish my homework',
    'have you tried the new restaurant?',
    'the movie had a surprising ending',
    'i’m learning to play the guitar',
    'the traffic was really heavy today',
    'i love spending time with family',
    'let’s plan a weekend getaway',
    'the kids have a new pet',
    'the cake turned out delicious',
    'i’m reading a fascinating book',
    'do you have any travel plans?',
    'the new store opened downtown',
    'i enjoyed our conversation',
    'the concert tickets sold out quickly',
    'i need to buy groceries',
    'let’s bake a cake together',
    'i’m interested in learning a new language',
    'how’s your new job going?',
    'i saw a great movie last night',
    'the weather is perfect for a picnic',
    'i’m taking a yoga class',
    'the museum has a new exhibit',
    'i’d love to hear your thoughts on this',
    'the library is a quiet place to study',
    'i’m working on a new project',
    'have you heard the latest podcast?',
    'let’s try a new restaurant this weekend',
    'the concert was a blast',
    'i’m planning to redecorate my room',
    'do you have any book recommendations?',
    'the new cafe has a cozy atmosphere',
    'i’m excited about the upcoming event',
    'the dog is learning new tricks',
    'i’m going to a workshop next week',
    'the beach is a great place to relax',
    'i’ve been practicing meditation',
    'the art gallery has some interesting pieces',
    'i’m thinking of starting a blog',
    'the local farmers market is open',
    'i’m trying out a new recipe',
    'the ski resort is busy this season',
    'i’m planning a surprise party',
    'the hiking trail is beautiful this time of year',
    'i’m working on my fitness goals',
    'the new bookshop has a great selection',
    'i’m attending a cooking class',
    'the sunset was breathtaking',
    'i’ve joined a book club',
    'the concert was really loud',
    'i’m learning to cook new dishes',
    'the park is a great place to unwind',
    'i’m visiting my family this weekend',
    'the spa is very relaxing',
    'i’m taking up painting as a hobby',
    'the bakery has fresh pastries',
    'i’m getting a new pet soon',
    'the new film was well-directed',
    'i’m studying for an exam',
    'the restaurant has a great atmosphere',
    'i’m organizing my workspace',
    'the new music album is fantastic',
    'i’m exploring new hiking trails',
    'the coffee shop has excellent espresso',
    'i’m planning a family vacation',
    'the neighborhood is very friendly',
    'i’m trying out a new workout routine',
    'the local theater has a new play',
    'i’m learning about digital photography',
    'the bookstore has a cozy reading nook',
    'i’m starting a new fitness challenge',
    'the aquarium has new exhibits',
    'i’m interested in sustainability projects',
    'the gym has a new class schedule',
    'i’m attending a tech conference',
    'the beach house is perfect for a getaway',
    'i’m reading a thriller novel',
    'the weekend weather looks promising',
    'i’m visiting a new city next month',
    'the local brewery has a new beer',
    'i’m working on a DIY project',
    'the new video game is very engaging',
    'i’m taking an online course',
    'the ice cream shop has unique flavors',
    'i’m planning a road trip',
    'the new gadget is a game-changer',
    'i’m trying out a new sport',
    'the local zoo has a new animal exhibit',
    'i’m reading a historical fiction novel',
    'the yoga studio has a new class',
    'i’m starting a new art project',
    'the new restaurant has a great menu',
    'i’m exploring local cultural events',
    'the new phone has amazing features',
    'i’m attending a music festival',
    'the new fitness app is motivating',
    'i’m working on a personal goal',
    'the park has a new playground',
    'i’m planning a camping trip',
    'the new book by my favorite author is out',
    'i’m learning about digital art',
    'the new restaurant has a fantastic view',
    'i’m visiting a historic site',
    'the new movie is worth watching',
    'i’m trying a new cooking technique',
    'the new fashion collection is stunning',
    'i’m working on a new business idea',
    'the local farmers market is thriving',
    'i’m exploring new music genres',
    'the new restaurant offers great vegan options',
    'i’m attending a motivational seminar',
    'the new car model has impressive features',
    'i’m trying out a new dance style',
    'the new park has beautiful walking trails',
    'i’m learning about home gardening',
    'the local art scene is vibrant',
    'i’m exploring new cuisines',
    'the new restaurant has a great ambiance',
    'i’m planning a weekend retreat',
    'the new game is very entertaining',
    'i’m visiting a famous landmark',
    'the new health trend is interesting',
    'i’m starting a new writing project',
    'the local music scene is lively',
    'i’m exploring new hobbies',
    'the new fashion trend is unique',
    'i’m attending a local workshop',
    'the new coffee blend is delicious',
    'i’m learning to play a new instrument',
    'the local theater has an exciting lineup',
    'i’m trying out a new recipe',
    'the new movie has a great cast',
    'i’m working on improving my skills',
    'the local library has new programs',
    'i’m planning a garden renovation',
    'the new art exhibit is impressive',
    'i’m exploring new travel destinations',
    'the local restaurant has a creative menu',
    'i’m starting a new fitness regimen',
    'the new tech gadget is innovative',
    'i’m attending a new class',
    'the local market has fresh produce',
    'i’m exploring local music talent',
    'the new restaurant offers unique dishes',
    'i’m trying a new relaxation technique',
    'the local cultural festival is exciting',
    'i’m learning a new skill',
    'the new coffee shop has a great atmosphere',
    'i’m working on a new project',
    'the local museum has interesting exhibits',
    'i’m exploring new workout routines',
    'the new store has a diverse selection',
    'i’m trying a new outdoor activity',
    'the local community center has new programs',
    'i’m attending a new seminar',
    'the new restaurant has an extensive wine list',
    'i’m working on a creative project',
    'the local park has a new playground',
    'i’m exploring new educational opportunities',
    'the new health food store is great',
    'i’m attending a local event',
    'the new movie has a compelling plot',
    'i’m starting a new hobby',
    'the local gym has a new fitness class',
    'i’m planning a new project',
    'the new art gallery has a great collection',
    'i’m exploring new outdoor adventures',
    'the local theater has a new show',
    'i’m working on a new venture',
    'the new music venue has a great lineup',
    'i’m learning a new language',
    'the local restaurant has a great brunch menu',
    'i’m trying out a new recipe',
    'the new park has beautiful scenery',
    'i’m attending a new workshop',
    'the new book is a must-read',
    'i’m working on a new art project',
    'the local zoo has a new exhibit',
    'i’m exploring new music styles',
    'the new restaurant has a cozy ambiance',
    'i’m starting a new exercise routine',
    'the local art gallery has an interesting display',
    'i’m trying a new culinary experience',
    'the new community center has exciting programs',
    'i’m planning a new trip',
]
def generatesentence(connect,length) -> str:
    # Split all sentences into words and create a dictionary of word transitions
    word_transitions = {}
    
    for sentence in connect:
        words = sentence.split()
        for i in range(len(words) - 1):
            if words[i] not in word_transitions:
                word_transitions[words[i]] = []
            word_transitions[words[i]].append(words[i + 1])
    
    # Choose a random starting word
    starting_word = random.choice(list(word_transitions.keys()))
    toreturn = starting_word
    
    current_word = starting_word
    # Generate a sentence with a length of up to 10 words
    for _ in range(length):
        if current_word in word_transitions:
            next_word = random.choice(word_transitions[current_word])
            toreturn += ' ' + next_word
            current_word = next_word
        else:
            break
    
    return toreturn


print(generatesentence(proceed,10))
